name: Add Label

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Determine label based on target branch
        id: determine-label
        run: |
          echo "${{github.event_name}}"
          if [[ "${{ github.event.pull_request.base.ref }}" == "next" ]]; then
            echo "label=2.x" >> $GITHUB_ENV
          elif [[ "${{ github.event.pull_request.base.ref }}" == "V3.0" ]]; then
            echo "label=3.x" >> $GITHUB_ENV
          else
            echo "label=" >> $GITHUB_ENV
          fi

      - name: Add label to Pull Request
        if: env.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.label }}